### PR TITLE
upgrade rtfeldman/elm-css

### PR DESCRIPTION
**Pull request by johnykifle**
Upgrade rtfeldman/elm-css to latest version `18.0.0`

### CODE REVIEW

**Comment by ken-matsui** [comment]
@johnykifle It looks like this is not an upgrade since you are narrowing down the version range. This package depends on `16.1.0 <= v < 19.0.0` of `rtfeldman/elm-css`, which includes `18.0.0`. Can you elaborate on why you want to make this change?

**Comment by johnykifle** [comment]
@ken-matsui  thanks 

I was trying to upgrade my `rtfeldman/elm-css` from `16.1.1` to latest `18.0.0`. But I got  this error

`Because ken-matsui/html-styled-extra 1.0.0 depends on rtfeldman/elm-css 16.1.0
<= v < 18.0.0 and this project depends on rtfeldman/elm-css 18.0.0, ken-
matsui/html-styled-extra 1.0.0 is incompatible with this project.`

**Comment by ken-matsui** [comment]
@johnykifle 

Oh, it is because I did not make a new release. The upstream supports `19.0.0` but this library's `1.0.0` does not support it.

I will make a new release later and thus close this issue. Thank you :)

**Comment by ken-matsui** [comment]
@johnykifle You should now be able to install `1.0.1` which support `19.0.0`

**Pull request closed without merging**
